module.exports = {
  "current.dmnhanvien": "server/his-server/api/SyncData/SyncEmployee",
  "current.dmdonvi": "server/his-server/api/SyncData/SyncDepartment",
  "current.dmphong": "server/his-server/api/SyncData/SyncRoom",
  "current.dmgiuongbenh": "server/his-server/api/SyncData/SyncBed",
  "current.dmloaicls": "server/his-server/api/SyncData/SyncMedSerType",
  "current.dmcls": "server/his-server/api/SyncData/SyncMedicalServiceItem",
  "current.dmkhocp": "server/his-server/api/SyncData/SyncStoreHouse",
  "current.dmkhoql": "server/his-server/api/SyncData/SyncInvType",
  "current.dmthuoc": "server/his-server/api/SyncData/SyncInventory",
  "current.bnnoitru-INSERT": "server/his-server/api/SyncData/SyncADM",
  "current.bnnoitru-UPDATE-RAVIEN=1": "server/his-server/api/SyncData/SyncDCHG",
  "current.qtdieutri": "server/his-server/api/Connect/TreatmentProcess",
  "current.chungtu": "server/his-server/api/Connect/CUTPPrescription",
  "current.chidinhcls": "server/his-server/api/Connect/CUTPParaClinRequest",
  "current.dmquocgia": "server/his-server/api/Connect/SyncCountry",
  "current.psdangky": "server/his-server/api/SyncData/SyncADM",
  "current.chuyenphong": "server/his-server/api/SyncData/SyncPATFR",
  "current.dmdantoc": "server/his-server/api/SyncData/SyncEthnic",
  "current.dmnghe": "server/his-server/api/SyncData/SyncOccupation",
  "current.dmicd": "server/his-server/api/SyncData/SyncICD",
};
